---
- name: Setup Apache HTTP Server on Fedora 42
  hosts: workstation1
  become: true

  tasks:
    - name: Ensure Apache (httpd) is installed
      dnf:
        name: httpd
        state: present

    - name: Ensure Apache service is enabled and started
      systemd:
        name: httpd
        enabled: true
        state: started

    - name: Open HTTP (port 80) in firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Ensure SELinux allows HTTPD traffic (optional, if SELinux is enforcing)
      sefcontext:
        target: '/var/www(/.*)?'
        setype: httpd_sys_content_t
        state: present
      when: ansible_selinux.status == "enabled"

    - name: Upload minimal homepage
      copy:
        dest: /var/www/html/index.html
        mode: 0644
        content: |
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Test</title>
            </head>
            <body>
              <h1>Welcome to Apache on Fedora!</h1>
            </body>
          <html>
